id: P001709
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105861
  title: སློབ་དཔོན་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་ཡིད་ཀྱི་མུན་སེལ།
  author: ''
  volumes:
    0210332d99a746218b5ff657c531bcea:
      image_group_id: I1PD105863
      title: ''
      volume_number: 1
      total_pages: 348
      base_file: v001.txt
